### ISSUE TITLE
hardware & runtime

### ISSUE THREAD

**Issue by Qichen98fly** [ExplainableML/AVCA-GZSL#1]
So what/How many gpus did you use for training each dataset? How much time for each one

**Comment by MerceaOtniel** [comment]
We used 1 GPU to train all networks for all datasets. The training time was shorter than 1 hour per method per dataset [f-vaegan-d2 took longer]. We fit the model on 2080ti.

**Comment by Qichen98fly** [comment]
And how about the same questions for feature extraction>

**Comment by MerceaOtniel** [comment]
Feature extraction took at most 2 days.

**Comment by Qichen98fly** [comment]
Thanks for letting me know. BTW, it is mentioned in readme.md that there is a pre-trained model called model.zip. So where can I download it? I didn't find it in this project

**Comment by Qichen98fly** [comment]
> Feature extraction took at most 2 days.

Thanks for letting me know
