### ISSUE TITLE
How to get pretrained_selavi_vgg_sound.pth

### ISSUE THREAD

**Issue by Qichen98fly** [ExplainableML/AVCA-GZSL#2]
Hi , I am wondering how to get the pth file in the instruction ' --weights_path <path_to_pretrained_selavi_vgg_sound.pth>'? I didn't find it from the referenced link.

Obtaining SeLaVi features
For obtaining the SeLaVi features we used the following command

python3 selavi_feature_extraction/get_clusters.py \
--root_dir <path_to_raw_videos> \
--weights_path <path_to_pretrained_selavi_vgg_sound.pth> \
--mode train \
--pretrained False \
--aud_sample_rate 44100 \
--use_mlp False \
--dataset {activity,ucf,vggsound} \
--headcount 2 \
--exp_desc <experiment_description> \
--output_dir <path_to_save_extracted_features> \
--batch_size 1 \
--workers 0

**Comment by MerceaOtniel** [comment]
Hi.

Here https://github.com/ExplainableML/AVCA-GZSL/tree/main/selavi_feature_extraction you can find a table named "Model Zoo". The last row in that table contain the model that you need to download ( https://dl.fbaipublicfiles.com/selavi/selavi_vgg_sound.pth). And after downloading, you just need to put the path of the model in the above command.
